module.exports.data = {
  pictures: [
    {
      _id: '0001',
      nameRu: 'Вейрон',
      nameEn: 'Veyron',
      link: 'https://placehold.jp/6000x4000.png',
      likes: [],
      created: 2024,
      priceRub: 10000,
      priceEur: 100,
      charactersRu: 'none',
      charactersEn: 'none',
      ownerRu: 'none',
      ownerEn: 'none',
      techniqueRu: 'Графика',
      techniqueEn: 'Graphic art',
      sizeRu: 'A4',
      sizeEn: 'A4',
      __v: 0,
      sections: ['01', '04', '08'],
      series: ['002'],
      landscape: true,
    },
    {
      _id: '0002',
      nameRu: 'Се Лянь целует Хуа Чэна',
      nameEn: 'Xie Lian kissing Hua Cheng',
      link: 'https://placehold.jp/350x600.png',
      likes: [],
      created: 2024,
      priceRub: 10000,
      priceEur: 100,
      charactersRu: 'none',
      charactersEn: 'none',
      ownerRu: 'none',
      ownerEn: 'none',
      techniqueRu: 'Графика',
      techniqueEn: 'Graphic art',
      sizeRu: 'A4',
      sizeEn: 'A4',
      __v: 0,
      sections: ['01', '04', '08'],
      series: ['003'],
      landscape: false,
    },
    {
      _id: '0003',
      nameRu: 'Рождение Умина',
      nameEn: 'Wu Ming՚s Birth',
      link: 'https://placehold.jp/700x400.png',
      likes: [],
      created: 2024,
      priceRub: 10000,
      priceEur: 100,
      charactersRu: 'none',
      charactersEn: 'none',
      ownerRu: 'none',
      ownerEn: 'none',
      techniqueRu: 'Графика, пастель',
      techniqueEn: 'Graphic art, pastel',
      sizeRu: 'A4',
      sizeEn: 'A4',
      __v: 0,
      sections: ['01', '04', '05'],
      series: ['003'],
      landscape: true,
    },
    {
      _id: '0004',
      nameRu: 'Меркурий',
      nameEn: 'Mercurius',
      link: 'https://placehold.jp/200x600.png',
      likes: [],
      created: 2024,
      priceRub: 10000,
      priceEur: 100,
      charactersRu: 'none',
      charactersEn: 'none',
      ownerRu: 'none',
      ownerEn: 'none',
      techniqueRu: 'Живопись',
      techniqueEn: 'Painting',
      sizeRu: 'A2',
      sizeEn: 'A2',
      __v: 0,
      sections: ['02', '04', '07', '08'],
      series: ['004'],
      landscape: false,
    },
    {
      _id: '0005',
      nameRu: 'Минотавр',
      nameEn: 'Minotaurus',
      link: 'https://placehold.jp/200x500.png',
      likes: [],
      created: 2024,
      priceRub: 10000,
      priceEur: 100,
      charactersRu: 'none',
      charactersEn: 'none',
      ownerRu: 'none',
      ownerEn: 'none',
      techniqueRu: 'Цифровое искусство, 3dскульпт',
      techniqueEn: 'digital art, 3dsculpt',
      sizeRu: 'A4',
      sizeEn: 'A4',
      __v: 0,
      sections: ['06', '08'],
      series: ['008'],
      landscape: false,
    },
    {
      _id: '0006',
      nameRu: 'Веста',
      nameEn: 'Vesta',
      link: 'https://placehold.jp/500x800.png',
      likes: [],
      created: 2024,
      priceRub: 10000,
      priceEur: 100,
      charactersRu: 'none',
      charactersEn: 'none',
      ownerRu: 'none',
      ownerEn: 'none',
      techniqueRu: 'Живопись',
      techniqueEn: 'Painting',
      sizeRu: 'A2',
      sizeEn: 'A2',
      __v: 0,
      sections: ['02', '04', '07', '08'],
      series: ['004'],
      landscape: false,
    },
    {
      _id: '0007',
      nameRu: 'Одуванчики',
      nameEn: 'Blowballs',
      link: 'https://placehold.jp/100x200.png',
      likes: [],
      created: 2024,
      priceRub: 10000,
      priceEur: 100,
      charactersRu: 'none',
      charactersEn: 'none',
      ownerRu: 'none',
      ownerEn: 'none',
      techniqueRu: 'Графика',
      techniqueEn: 'Graphic art',
      sizeRu: 'A4',
      sizeEn: 'A4',
      __v: 0,
      sections: ['01', '09'],
      series: ['008'],
      landscape: false,
    },
    {
      _id: '0008',
      nameRu: 'Лисята-фенеки',
      nameEn: 'Fennec fox puppies',
      link: 'https://placehold.jp/600x400.png',
      likes: [],
      created: 2024,
      priceRub: 10000,
      priceEur: 100,
      charactersRu: 'none',
      charactersEn: 'none',
      ownerRu: 'none',
      ownerEn: 'none',
      techniqueRu: 'Графика, цветные карандаши',
      techniqueEn: 'Graphic art, pencil crayon',
      sizeRu: 'A4',
      sizeEn: 'A4',
      __v: 0,
      sections: ['01', '09'],
      series: ['008'],
      landscape: true,
    },
    {
      _id: '0009',
      nameRu: 'Замок долголетия',
      nameEn: 'Longevity Locket',
      link: 'https://placehold.jp/1200x800.png',
      likes: [],
      created: 2024,
      priceRub: 10000,
      priceEur: 100,
      charactersRu: 'none',
      charactersEn: 'none',
      ownerRu: 'none',
      ownerEn: 'none',
      techniqueRu: 'Цифровое искусство',
      techniqueEn: 'Digital art',
      sizeRu: 'A4',
      sizeEn: 'A4',
      __v: 0,
      sections: ['04', '06', '05'],
      series: ['003'],
      landscape: true,
    },
    {
      _id: '0010',
      nameRu: 'Гений смерти',
      nameEn: 'Genius of Death',
      link: 'https://placehold.jp/400x600.png',
      likes: [],
      created: 2024,
      priceRub: 10000,
      priceEur: 100,
      charactersRu: 'none',
      charactersEn: 'none',
      ownerRu: '"Рога и копыта"',
      ownerEn: '"Horns and hooves"',
      techniqueRu: 'Графика',
      techniqueEn: 'Graphic art',
      sizeRu: 'A4',
      sizeEn: 'A4',
      __v: 0,
      sections: ['01', '08', '03'],
      series: ['008'],
      landscape: false,
    },
  ],

  sections: [
    {
      _id: '01',
      nameRu: 'Рисунки',
      nameEn: 'Graphic art',

      __v: 0,
    },
    {
      _id: '02',
      nameRu: 'Живопись',
      nameEn: 'Painting',
      __v: 0,
    },

    {
      _id: '03',
      nameRu: 'Дизайны',
      nameEn: 'Design',
      __v: 0,
    },
    {
      _id: '04',
      nameRu: 'Серии',
      nameEn: 'Series',
      __v: 0,
    },
    {
      _id: '05',
      nameRu: 'Книжные иллюстрации',
      nameEn: 'Book illustrations',
      __v: 0,
    },
    {
      _id: '06',
      nameRu: 'Цифровое искусство',
      nameEn: 'Digital art',
      __v: 0,
    },
    {
      _id: '07',
      nameRu: 'Выставки',
      nameEn: 'Expositions',
      __v: 0,
    },
    {
      _id: '08',
      nameRu: 'На продажу',
      nameEn: 'For sale',
      __v: 0,
    },
    {
      _id: '09',
      nameRu: 'Скетчи',
      nameEn: 'Sketches',
      __v: 0,
    },
  ],

  series: [
    {
      _id: '001',
      nameRu: 'Шерлок Холмс',
      nameEn: 'Sherlock Holmes',
      __v: 0,
    },
    {
      _id: '002',
      nameRu: 'Лошади',
      nameEn: 'Horses',
      __v: 0,
    },
    {
      _id: '003',
      nameRu: 'Благословение небожителей',
      nameEn: 'Heaven Official՚s Blessing',
      __v: 0,
    },
    {
      _id: '004',
      nameRu: 'Пантеон римских богов',
      nameEn: 'Ancient Roman Gods՚ Pantheon',
      __v: 0,
    },
    {
      _id: '005',
      nameRu: 'Рим',
      nameEn: 'Rome',
      __v: 0,
    },
    {
      _id: '006',
      nameRu: 'Космоолухи',
      nameEn: 'Cosmoooluhi',
      __v: 0,
    },
    {
      _id: '007',
      nameRu: 'Сверхъестественное',
      nameEn: 'Supernatural',
      __v: 0,
    },
    {
      _id: '008',
      nameRu: 'Вне серий',
      nameEn: 'No series',
      __v: 0,
    },
  ],
};

module.exports.admin = {
  _id: '67272b09f32960ec4b24a8fd',
  name: 'Olga-admin',
  email: 'lov800@yandex.ru',
  verified: true,
  token: '',
  admin: true,
  __v: 0,
};

module.exports.user = {
  _id: '67272b09f32960ec4b24a8fe',
  name: 'Olga-user',
  email: 'lov801@yandex.ru',
  verified: true,
  token: '',
  admin: false,
  __v: 0,
};
